/******************************************************************************
 *
 * Module: PORt
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for Port Module.
 *
 * Author: Rana Tarek
 ******************************************************************************/

#include "Port.h"
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

const Port_ConfigType Port_Configuration = {
/*Port A Default Configuration*/
PORTA_NUM, PORT_A_PIN_0,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_1,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_2,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_3,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_4,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_5,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_6,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTA_NUM, PORT_A_PIN_7,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

/*Port B Default Configuration*/
PORTB_NUM, PORT_B_PIN_0,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_1,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_2,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_3,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_4,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_5,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_6,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTB_NUM, PORT_B_PIN_7,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

/*Port C Default Configuration*/
PORTC_NUM, PORT_C_PIN_0,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTC_NUM, PORT_C_PIN_1,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTC_NUM, PORT_C_PIN_2,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTC_NUM, PORT_C_PIN_3,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTC_NUM, PORT_C_PIN_4,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

/*Ports LED1 Configuration*/
PortConf_LED1_PORT_NUM,
PortConf_LED1_PIN_NUM,
PortConf_LED1_PIN_DIRECTION,
PortConf_LED1_PIN_initial,
PortConf_LED1_PIN_DIRECTION_CHANGEABLE,
PortConf_LED1_PIN_MODE_CHANGEABLE,

PORTC_NUM, PORT_C_PIN_6,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTC_NUM, PORT_C_PIN_7,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

/*Port D Default Configuration*/
PORTD_NUM, PORT_D_PIN_0,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTD_NUM, PORT_D_PIN_1,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

/*Ports BUTTON Configuration*/
PortConf_BUTTON1_PORT_NUM,
PortConf_BUTTON1_PIN_NUM,
PortConf_BUTTON1_PIN_DIRECTION,
PortConf_BUTTON1_PIN_RESISTOR,
PortConf_BUTTON1_DIRECTION_CHANGEABLE,
PortConf_BUTTON1_MODE_CHANGEABLE,

PORTD_NUM, PORT_D_PIN_3,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTD_NUM, PORT_D_PIN_4,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTD_NUM, PORT_D_PIN_5,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTD_NUM, PORT_D_PIN_6,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE,

PORTD_NUM, PORT_D_PIN_7,
PortConf_DEFAULT_PIN_DIRECTION,
PortConf_DEFAULT_PIN_INITIAL_VALUE,
PortConf_DEFAULT_DIRECTION_CHANGEABLE,
PortConf_DEFAULT_PIN_MODE_CHANGEABLE, };

